// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mvctest.Models;

#nullable disable

namespace mvctest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("mvctest.Models.TodoItem", b =>
                {
                    b.Property<int>("TodoItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TodoItemId"));

                    b.Property<bool>("Done")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TodoListId")
                        .HasColumnType("int");

                    b.HasKey("TodoItemId");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            TodoItemId = 1,
                            Done = false,
                            Name = "Gungtomte",
                            TodoListId = 1
                        },
                        new
                        {
                            TodoItemId = 2,
                            Done = false,
                            Name = "HusTome",
                            TodoListId = 1
                        },
                        new
                        {
                            TodoItemId = 3,
                            Done = false,
                            Name = "SmåTomtar",
                            TodoListId = 1
                        },
                        new
                        {
                            TodoItemId = 4,
                            Done = false,
                            Name = "grupp 1",
                            TodoListId = 2
                        },
                        new
                        {
                            TodoItemId = 5,
                            Done = false,
                            Name = "grupp3",
                            TodoListId = 2
                        });
                });

            modelBuilder.Entity("mvctest.Models.TodoList", b =>
                {
                    b.Property<int>("TodoListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TodoListId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TodoListId");

                    b.ToTable("TodoLists");

                    b.HasData(
                        new
                        {
                            TodoListId = 1,
                            Name = "Produkter"
                        },
                        new
                        {
                            TodoListId = 2,
                            Name = "Workshop"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
